### ISSUE TITLE
operator catalog initialization test fails

### ISSUE THREAD

**Issue by jeyaramashok** [redhat-operator-ecosystem/operator-test-playbooks#2]
I am trying to run the playbooks locally and having some issues. One of the failure happens in [operator_catalog_initialization_test](https://github.com/redhat-operator-ecosystem/operator-test-playbooks/blob/master/roles/operator_catalog_initialization_test/tasks/main.yml#L72)

```
"error loading manifests from directory: error loading package into db: UNIQUE constraint failed: package.name"
```
Command run:
```
ansible-playbook -vv -i "localhost," \
	--connection=local \
	-e run_catalog_init=true \
	-e quay_token=<FIXME> \
	-e quay_namespace=jeyaramashok \
        -e kubeconfig_path=~/.kube/config \
        -e operator_dir="~/pingpong-operator" \
	local-test-operator.yml
```

here is the full log of [catalog-init-debug-release-4.2.txt](https://github.com/redhat-operator-ecosystem/operator-test-playbooks/files/4289948/catalog-init-debug-release-4.2.txt)

I am able to get past this by setting `-e run_catalog_init=false` but wanted to bring this up if this would affect any following steps

**Comment by dirgim** [comment]
Hi, the playbook fails if a test failed, like in this case. As far as I can see, that was a legitimate failure when running the catalog init test on the operator, indicating there is a package name conflict when trying to initialize an operator catalog.

**Comment by jeyaramashok** [comment]
this is the operator manifest I'm using [pingpong-operator.zip](https://github.com/redhat-operator-ecosystem/operator-test-playbooks/files/4313321/pingpong-operator.zip)

package.yaml
```
channels:
- currentCSV: pingpong-operator.v0.1.0
  name: alpha
defaultChannel: stable
packageName: pingpong-operator
```

does this package already exist in the catalog ?

**Comment by jeyaramashok** [comment]
how should I fix this?

**Comment by dirgim** [comment]
If the package already exists in the production catalog, the test replaces it with the manifest that's being tested, so it shouldn't be a problem. I'm not sure what the issue is currently. The manifest you provided has only the package file in it, so I'm not able to reproduce the problem.

**Comment by jeyaramashok** [comment]
apologies I missed `-r` flag when I created the zip to upload here . here is right zip file 
[pingpong-operator.zip](https://github.com/redhat-operator-ecosystem/operator-test-playbooks/files/4313916/pingpong-operator.zip)

its not in production catalog ( i assume production means certified / ecosystem catalog) , I created the operator locally on my computer

**Comment by jeyaramashok** [comment]
@scoheb I reran the test `-e run_catalog_init=true` after fixing my channel name in package.yaml and I still get the same error

**Comment by cvp-ops** [comment]
@jeyaramashok Can you link us to your up-to-date zip? The ones I download from this issue or the closed one all point a stable while the alpha channel points to 0.1.0 even though latest CSV is 0.1.1

**Comment by jeyaramashok** [comment]
sorry, here is the right link [pingpong-operator.zip](https://github.com/redhat-operator-ecosystem/operator-test-playbooks/files/4321482/pingpong-operator.zip)

I have also removed the 0.1.1 version to avoid confusion

these are the contents
```
$ unzip -l pingpong-operator.zip
Archive:  pingpong-operator.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  03-10-2020 12:23   0.1.0/
      116  03-10-2020 14:46   pingpong-operator.package.yaml
     1197  02-24-2020 23:02   0.1.0/jey.com_pingpongs_crd.yaml
     4899  02-25-2020 23:38   0.1.0/pingpong-operator.v0.1.0.clusterserviceversion.yaml
---------                     -------
     6212                     4 files
```

```
channels:
- currentCSV: pingpong-operator.v0.1.0
  name: alpha
defaultChannel: alpha
packageName: pingpong-operator
```

ran with this directory layout, the catalog initialization test fails. I couldn't find what's missing.

here is the playbook log [run-2020-03-11_162208.log](https://github.com/redhat-operator-ecosystem/operator-test-playbooks/files/4321529/run-2020-03-11_162208.log)

here is zip of `/tmp/operator-test`  [pingpong-operator.zip](https://github.com/redhat-operator-ecosystem/operator-test-playbooks/files/4321533/pingpong-operator.zip)

**Comment by scoheb** [comment]
@jeyaramashok 

Both myself and @dirgim tried testing your operator zip file and the catalog init passed for us.

Please ensure you are setting:

`-e production_quay_namespace="certified-operators" `

Please re-run with that setting and let us know.

**Comment by jeyaramashok** [comment]
Thanks Scott, I've now changed to set `-e production_quay_namespace="certified-operators"`

I ran into the catalog initialization failure again. Then I changed my directory structure looking at other manifests. That seemed to fix the problem.

So initially I had version directory `0.1.0` with crd & csv like this:
```
$ ls pingpong-operator/
total 4.0K
drwxr-x--- 2 jey 137 Mar  4 12:28 0.1.0/
-rw-r--r-- 1 jey 117 Mar 10 12:47 pingpong-operator.package.yaml
```

Then I removed that version dir `0.1.0` and made it flat:
```
$ ls pingpong-operator/
total 16K
-rw-r--r-- 1 jey 4.8K Mar 18 12:05 pingpong-operator.v0.1.0.clusterserviceversion.yaml
-rw-r--r-- 1 jey  116 Mar 18 12:05 pingpong-operator.package.yaml
-rw-r--r-- 1 jey 1.2K Mar 18 12:05 jey.com_pingpongs_crd.yaml
```

Then playbooks ran succesfully.
