### ISSUE TITLE
Scorecard Fails with empty alm-examples

### ISSUE THREAD

**Issue by mathianasj** [redhat-operator-ecosystem/operator-test-playbooks#9]
When trying to test an operator that does not create and CRDs, the scorecard test fails with 

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/tmp/operator-test/bin/oc delete -f /tmp/operator-test/scorecard-cr-files/first.cr.yaml --ignore-not-found=true --grace-period=60 --timeout=120s", "delta": "0:00:00.096581", "end": "2020-04-14 12:30:22.673926", "msg": "non-zero return code", "rc": 1, "start": "2020-04-14 12:30:22.577345", "stderr": "error: unable to decode \"/tmp/operator-test/scorecard-cr-files/first.cr.yaml\": Object 'Kind' is missing in '{\"metadata\":{\"namespace\":\"test-operator\"}}'", "stderr_lines": ["error: unable to decode \"/tmp/operator-test/scorecard-cr-files/first.cr.yaml\": Object 'Kind' is missing in '{\"metadata\":{\"namespace\":\"test-operator\"}}'"], "stdout": "", "stdout_lines": []}

Expected to pass as the operator does not require creating resources.

This is also blocking the automated process from testing operators when PRs are created to the community-operators.

**Comment by lslebodn** [comment]
Would you mind share content of the file `/tmp/operator-test/scorecard-cr-files/first.cr.yaml`?

@dirgim or do you know answer just from the output? :-)

**Comment by dirgim** [comment]
We will implement a change that checks if the operator has any owned CRDs - if it does not, the scorecard test will be skipped.

**Comment by mathianasj** [comment]
Not sure if it's still necessary but want to share the file's contents

`metadata:
  namespace: test-operator`

**Comment by dirgim** [comment]
Right, that's an artifact of there not being an alm-example in the first place. You mentioned your operator failing in the community operator pipeline, do you have a link to the PR for it so we can debug?

**Comment by mathianasj** [comment]
https://github.com/operator-framework/community-operators/pull/1537
